import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#f9f9f6",
        foreground: "#1a1c1b",
        "on-secondary-fixed": "#00006e",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeeb",
        "surface-container-highest": "#e2e3e0",
        "primary": "#8f4e00",
        "inverse-on-surface": "#f1f1ee",
        "surface-bright": "#f9f9f6",
        "inverse-primary": "#ffb77a",
        "secondary-fixed": "#e0e0ff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#bfc2ff",
        "tertiary-container": "#5dc849",
        "surface-container-low": "#f4f4f1",
        "outline": "#887364",
        "tertiary-fixed": "#8dfc75",
        "on-surface": "#1a1c1b",
        "tertiary-fixed-dim": "#72de5c",
        "on-primary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#035300",
        "inverse-surface": "#2f312f",
        "secondary": "#4b53bc",
        "tertiary": "#056e00",
        "surface": "#f9f9f6",
        "surface-container-high": "#e8e8e5",
        "outline-variant": "#dbc2b0",
        "on-tertiary-container": "#035000",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "primary-container": "#ff9933",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "primary-fixed": "#ffdcc2",
        "surface-tint": "#8f4e00",
        "surface-variant": "#e2e3e0",
        "secondary-container": "#8991fe",
        "on-background": "#1a1c1b",
        "on-secondary-container": "#1b218f",
        "on-error": "#ffffff",
        "surface-dim": "#dadad7",
        "on-primary-container": "#693800",
        "primary-fixed-dim": "#ffb77a",
        "on-tertiary-fixed": "#012200",
        "on-surface-variant": "#554336",
        "on-secondary-fixed-variant": "#3239a3",
        "on-primary-fixed-variant": "#6d3a00",
        "brand-navy": "#000080",
        "brand-saffron": "#FF9933",
        "brand-green": "#138808",
        "brand-charcoal": "#1A1A1A",
        "brand-off-white": "#FAFAF7"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-max-width": "1280px",
        "base": "8px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Tiro Devanagari Hindi"],
        "display-lg-mobile": ["Tiro Devanagari Hindi"],
        "title-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Tiro Devanagari Hindi"],
        "headline-md": ["Tiro Devanagari Hindi"]
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "500" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
};
export default config;
